name: Fetch YouTube Videos to Jekyll Posts

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    - cron: '0 5 * * *' # Runs daily at 5 AM UTC. Adjust cron schedule as needed.
  # push: # Uncomment if you want to run on push to main/master
  #   branches:
  #     - main # or your default branch e.g. master

jobs:
  fetch-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit and push changes back to the repo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Python 3.9 or higher is required for built-in zoneinfo

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client python-dateutil isodate PyYAML

      - name: Run YouTube fetch script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: UCRkqSGyfZkhOzZIHjlgBXcQ # Your YouTube Channel ID
        run: python .github/scripts/fetch_youtube_videos.py

      - name: Commit and push new posts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - YouTube Fetch"
          git add _posts/*.md
          # Check if there are any staged changes to commit
          if git diff --staged --quiet; then
            echo "No new video posts to commit."
          else
            git commit -m "CI: Add new YouTube video posts from channel"
            echo "Pushing changes..."
            git push
          fi